Project/config/routes.rb
Rails.application.routes.draw do

  resources :books do
    resources :comments
  end  
  
  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :homes
  resources :notes
  resources :books
  resources :categories
  resources :subjects

 root 'homes#index'

end

Project/app/models/book.rb
class Book < ActiveRecord::Base
	mount_uploader :cover, CoverUploader

	has_many :comments

	belongs_to :category
	belongs_to :subject
	belongs_to :user

  def category_branch
  	category.try(:branch)
  end	

  def category_branch=(branch)
  	self.category = Category.find_or_create_by_branch(branch) if branch.present?
  end
end

Project/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :store_current_location, :unless => :devise_controller?
  before_filter :authenticate_user!, :except => [:show,:index]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  helper_method :for1 ,:for2

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @categories = Category.all
    @subjects = Subject.all
  end

  
  # GET /books/1
  # GET /books/1.json
  def show
    @books = Book.all
    @categories = Category.all
    @subjects = Subject.all
    @users = User.all
  end

  # GET /books/new
  def new
    @book = Book.new
    @categories = Category.all
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :publisher, :category_id, :subject_id, :price, :user_id, :description, :cover)
    end

    def store_current_location
      store_location_for(:user, request.url)
    end

    def after_sign_out_path_for(resource)
      request.referrer || root_path
    end
end

Project/app/helpers/books_helper.rb
module BooksHelper
end

Project/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :category_branch %><br>
    <%= f.text_field :category_branch, data: {autocomplete_source: categories_path}%>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.collection_select :subject_id, Subject.order(:subject_name),:id,:subject_name, include_blank: true %>
    <%= f.select :subject_id, ['option1', 'option2']%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Project/app/views/books/edit.html.erb
<% if !current_user.nil? %>
	<% if current_user.admin? %>
		<%= render 'form' %>
		<%= link_to 'Show', @book %> |
		<%= link_to 'Back', books_path %>
	<% elsif current_user.id == @book.user_id %>
		<%= render 'form' %>
		<%= link_to 'Show', @book %> |	
		<%= link_to 'Back', books_path %>
	<% else %>
		<h1>You can't access this Web page</h1>
	<% end %>
<% else %>
	<h1>You can't access this Web page</h1>
<% end %>

Project/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>





<div id="containers">
  <div id="left-columns">

  </div>


  <div id="right-columns">
    <div class="minimum_size" >
      <% @books.each do |book| %>
      <a href="/books/<%=book.id%>"">
        <div class=" col-lg-3 item height_class">
          <br>
          <%= image_tag(book.cover.url,height:150,width:150) if book.cover %>
          <h3><%= book.name %><br></h3> 
          Author : <%= book.author %><br>
          Publiisher : <%= book.publisher %>
          <form action="https://en.wikipedia.org/wiki/Anno_Domini" style="position: absolute; align-items: center; bottom: 0;">
            <input type="submit" value="Contact" class="btn btn-success marginTop" />
          </form>

        </div>
      </a>

      <% end %>
    </div>
  </div>

</div>
<%= link_to 'New Book', new_book_path %>

Project/app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

Project/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Category:</strong>
    <%= @book.category.branch %>
   
</p>

<p>
  <strong>Subject:</strong>
  <%= @book.subject.subject_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Posted By:</strong>
 <%= @book.user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Cover:</strong>
  <%= image_tag(@book.cover.url,height:100,width:100) if @book.cover %>
</p>




<h2>Comments</h2>
<% @book.comments.each do |comment|%>
<p>
  <strong>Commenter:</strong>
  <% @users.each do |use| %>
    <% if @book.user_id == use.id %>
      <%= use.name %>
    <% end %>
  <% end %>    
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% end %>

<h2>Add a Comment</h2>

<%= form_for([@book, @book.comments.build]) do |f| %>


<p>
  <%= f.label :body %><br/>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>
<% if !current_user.nil? %>
<% if current_user.admin? %>
  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Destroy', @book, method: :delete, data: {confirm:'Are you sure you want to delete this POST?'} %>
<% elsif current_user.id == @book.user_id %>
  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Destroy', @book, method: :delete, data: {confirm:'Are you sure you want to delete this POST?'} %>
<% end %>
<% end %>

<%= link_to 'Back', books_path %>